api.current_version=${project.version}
api.min_version=1.0
db.version=31

# --- 以下是你新增的内容 ---
storage.path=/var/docs
db.url=jdbc:h2:file:/var/docs/teedy;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
db.user=sa
db.password=