alter table T_DOCUMENT add column DOC_SUBJECT_C varchar(500);
alter table T_DOCUMENT add column DOC_IDENTIFIER_C varchar(500);
create memory table T_VOCABULARY ( VOC_ID_C varchar(50) not null, VOC_VALUE_C varchar(100) not null, VOC_ORDER_N int not null );

insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Collection', 0);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Dataset', 1);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Event', 2);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Image', 3);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Interactive Resource', 4);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Moving Image', 5);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Physical Object', 6);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Service', 7);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Software', 8);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Sound', 9);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Still Image', 10);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('TYPE', 'Text', 11);

insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Afghanistan', 0);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Åland Islands', 1);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Albania', 2);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Algeria', 3);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'American Samoa', 4);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Andorra', 5);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Angola', 6);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Anguilla', 7);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Antarctica', 8);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Antigua and Barbuda', 9);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Argentina', 10);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Armenia', 11);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Aruba', 12);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Australia', 13);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Austria', 14);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Azerbaijan', 15);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bahamas', 16);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bahrain', 17);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bangladesh', 18);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Barbados', 19);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Belarus', 20);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Belgium', 21);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Belize', 22);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Benin', 23);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bermuda', 24);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bhutan', 25);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bolivia (Plurinational State of)', 26);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bonaire, Sint Eustatius and Saba', 27);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bosnia and Herzegovina', 28);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Botswana', 29);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bouvet Island', 30);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Brazil', 31);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'British Indian Ocean Territory', 32);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Brunei Darussalam', 33);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Bulgaria', 34);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Burkina Faso', 35);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Burundi', 36);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Cabo Verde', 37);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Cambodia', 38);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Cameroon', 39);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Canada', 40);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Cayman Islands', 41);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Central African Republic', 42);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Chad', 43);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Chile', 44);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'China', 45);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Christmas Island', 46);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Cocos (Keeling) Islands', 47);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Colombia', 48);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Comoros', 49);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Congo', 50);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Congo (Democratic Republic of the)', 51);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Cook Islands', 52);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Costa Rica', 53);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Côte d''Ivoire', 54);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Croatia', 55);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Cuba', 56);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Curaçao', 57);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Cyprus', 58);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Czech Republic', 59);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Denmark', 60);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Djibouti', 61);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Dominica', 62);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Dominican Republic', 63);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Ecuador', 64);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Egypt', 65);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'El Salvador', 66);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Equatorial Guinea', 67);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Eritrea', 68);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Estonia', 69);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Ethiopia', 70);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Falkland Islands (Malvinas)', 71);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Faroe Islands', 72);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Fiji', 73);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Finland', 74);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'France', 75);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'French Guiana', 76);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'French Polynesia', 77);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'French Southern Territories', 78);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Gabon', 79);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Gambia', 80);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Georgia', 81);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Germany', 82);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Ghana', 83);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Gibraltar', 84);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Greece', 85);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Greenland', 86);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Grenada', 87);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Guadeloupe', 88);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Guam', 89);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Guatemala', 90);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Guernsey', 91);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Guinea', 92);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Guinea-Bissau', 93);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Guyana', 94);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Haiti', 95);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Heard Island and McDonald Islands', 96);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Holy See', 97);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Honduras', 98);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Hong Kong', 99);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Hungary', 100);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Iceland', 101);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'India', 102);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Indonesia', 103);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Iran (Islamic Republic of)', 104);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Iraq', 105);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Ireland', 106);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Isle of Man', 107);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Israel', 108);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Italy', 109);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Jamaica', 110);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Japan', 111);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Jersey', 112);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Jordan', 113);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Kazakhstan', 114);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Kenya', 115);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Kiribati', 116);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Korea (Democratic People''s Republic of)', 117);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Korea (Republic of)', 118);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Kuwait', 119);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Kyrgyzstan', 120);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Lao People''s Democratic Republic', 121);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Latvia', 122);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Lebanon', 123);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Lesotho', 124);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Liberia', 125);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Libya', 126);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Liechtenstein', 127);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Lithuania', 128);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Luxembourg', 129);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Macao', 130);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Macedonia (the former Yugoslav Republic of)', 131);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Madagascar', 132);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Malawi', 133);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Malaysia', 134);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Maldives', 135);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Mali', 136);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Malta', 137);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Marshall Islands', 138);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Martinique', 139);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Mauritania', 140);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Mauritius', 141);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Mayotte', 142);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Mexico', 143);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Micronesia (Federated States of)', 144);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Moldova (Republic of)', 145);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Monaco', 146);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Mongolia', 147);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Montenegro', 148);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Montserrat', 149);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Morocco', 150);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Mozambique', 151);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Myanmar', 152);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Namibia', 153);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Nauru', 154);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Nepal', 155);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Netherlands', 156);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'New Caledonia', 157);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'New Zealand', 158);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Nicaragua', 159);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Niger', 160);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Nigeria', 161);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Niue', 162);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Norfolk Island', 163);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Northern Mariana Islands', 164);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Norway', 165);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Oman', 166);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Pakistan', 167);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Palau', 168);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Palestine, State of', 169);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Panama', 170);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Papua New Guinea', 171);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Paraguay', 172);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Peru', 173);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Philippines', 174);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Pitcairn', 175);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Poland', 176);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Portugal', 177);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Puerto Rico', 178);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Qatar', 179);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Réunion', 180);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Romania', 181);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Russian Federation', 182);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Rwanda', 183);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Saint Barthélemy', 184);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Saint Helena, Ascension and Tristan da Cunha', 185);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Saint Kitts and Nevis', 186);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Saint Lucia', 187);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Saint Martin (French part)', 188);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Saint Pierre and Miquelon', 189);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Saint Vincent and the Grenadines', 190);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Samoa', 191);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'San Marino', 192);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Sao Tome and Principe', 193);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Saudi Arabia', 194);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Senegal', 195);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Serbia', 196);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Seychelles', 197);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Sierra Leone', 198);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Singapore', 199);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Sint Maarten (Dutch part)', 200);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Slovakia', 201);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Slovenia', 202);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Solomon Islands', 203);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Somalia', 204);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'South Africa', 205);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'South Georgia and the South Sandwich Islands', 206);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'South Sudan', 207);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Spain', 208);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Sri Lanka', 209);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Sudan', 210);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Suriname', 211);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Svalbard and Jan Mayen', 212);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Swaziland', 213);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Sweden', 214);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Switzerland', 215);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Syrian Arab Republic', 216);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Taiwan, Province of China', 217);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Tajikistan', 218);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Tanzania, United Republic of', 219);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Thailand', 220);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Timor-Leste', 221);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Togo', 222);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Tokelau', 223);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Tonga', 224);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Trinidad and Tobago', 225);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Tunisia', 226);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Turkey', 227);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Turkmenistan', 228);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Turks and Caicos Islands', 229);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Tuvalu', 230);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Uganda', 231);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Ukraine', 232);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'United Arab Emirates', 233);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'United Kingdom of Great Britain and Northern Ireland', 234);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'United States of America', 235);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'United States Minor Outlying Islands', 236);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Uruguay', 237);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Uzbekistan', 238);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Vanuatu', 239);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Venezuela (Bolivarian Republic of)', 240);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Viet Nam', 241);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Virgin Islands (British)', 242);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Virgin Islands (U.S.)', 243);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Wallis and Futuna', 244);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Western Sahara', 245);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Yemen', 246);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Zambia', 247);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('COVERAGE', 'Zimbabwe', 248);

insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('RIGHTS', 'All Rights Reserved', 0);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('RIGHTS', 'Public Domain', 1);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('RIGHTS', 'Attribution-NonCommercial-ShareAlike License', 2);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('RIGHTS', 'Attribution-NonCommercial License', 3);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('RIGHTS', 'Attribution-NonCommercial-NoDerivs License', 4);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('RIGHTS', 'Attribution License', 5);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('RIGHTS', 'Attribution-ShareAlike License', 6);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('RIGHTS', 'Attribution-NoDerivs License', 7);
insert into T_VOCABULARY(VOC_ID_C, VOC_VALUE_C, VOC_ORDER_N) values('RIGHTS', 'No known copyright restrictions', 8);

update T_CONFIG set CFG_VALUE_C = '6' where CFG_ID_C = 'DB_VERSION';
